[project]
name = "FitNest"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.fit-token]
path = "contracts/fit-token.clar"
depends_on = []

[contracts.workout-nft]
path = "contracts/workout-nft.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
